#!/usr/bin/env ruby

require "saml/kit/cli"

Saml::Kit.configure do |configuration|
  configuration.registry = Saml::Kit::Cli::YamlRegistry.new(File.join(Dir.home, ".samlkitrc"))
  configuration.logger.level = Logger::FATAL
end

Saml::Kit::Cli::Application.start(ARGV)
